{% set python_min = '3.10' %}
{% set name = "txl-editors" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_editors-{{ version }}.tar.gz
  sha256: 5e9f55562340a1f710fe98dc9e3a905b29789e37bbf7babaa0537a3bba1b4f5e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_editors

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/editors
  summary: TXL plugin for editors
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/editors
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
